name: CI - Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Verificar versión de Java
        run: java -version

      - name: Instalar dependencias
        run: mvn clean install -U -DskipTests

      - name: Ejecutar pruebas Selenium
        run: mvn test

      - name: Verificar si Allure generó resultados
        run: ls -la target/allure-results || echo "Allure results directory not found!"

      - name: Generar reportes Allure
        run: mvn allure:report

      - name: Guardar reportes como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: target/site/allure-maven/index.html
