name: CI - Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java y Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: 'maven'

      - name: Instalar Allure manualmente
        run: |
          curl -o allure-2.21.0.tgz -OLs https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz
          tar -zxvf allure-2.21.0.tgz
          sudo mv allure-2.21.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
          allure --version

      - name: Instalar dependencias
        run: mvn install -DskipTests

      - name: Ejecutar pruebas Selenium
        run: mvn test

      - name: Generar reportes Allure
        run: mvn allure:report

      - name: Guardar reportes como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: target/site/allure-maven/
